### ISSUE TITLE
Outdated swift-sh version & question about Homebrew formula location

### ISSUE THREAD

**Issue by lukaskubanek** [mxcl/homebrew-made#4]
Hi @mxcl, I've just noticed that the version of swift-sh [in the fomula in this repository](https://github.com/mxcl/homebrew-made/blob/master/swift-sh.rb) (1.11.0) does not match with the latest version of swift-sh in its own repository (1.12.0).

More generally, I'd like to ask why there is a separate repository which contains only this very formula? I like the way Beak handles it by storing the formula directly [in its repository](https://github.com/yonaskolb/Beak/blob/master/Formula/beak.rb). They even have [a script](https://github.com/yonaskolb/Beak/blob/master/beak.swift#L35-L60) in place which updates the formula. I guess this could make it easier to keep the Homebrew formula up to date.

PS: I just tried installing all three main tools for this task (swift-sh, Marathon & Beak) via Homebrew and the latest version was picked only for Beak.

**Comment by mxcl** [comment]
> Hi @mxcl, I've just noticed that the version of swift-sh in the fomula in this repository (1.11.0) does not match with the latest version of swift-sh in its own repository (1.12.0).

Seems my CI job that updates the formula failed:

https://travis-ci.com/mxcl/swift-sh/builds/108774577

Sorry about that. I'm trying again.

> More generally, I'd like to ask why there is a separate repository which contains only this very formula? I like the way Beak handles it by storing the formula directly in its repository. They even have a script in place which updates the formula. I guess this could make it easier to keep the Homebrew formula up to date.

Obviously I originally designed the Homebrew Tap system, and at the time it had to be a repo named `homebrew-` something to enforce discovery. Apparently this is no longer the case.

Either way, I want a separate repo so when I release new tools in future I have one tap to contain the formula.

As already said, I already update the formula via CI.

> PS: I just tried installing all three main tools for this task (swift-sh, Marathon & Beak) via Homebrew and the latest version was picked only for Beak.

John Sundell doesn't support Homebrew for Marathon. As said `swift-sh` was behind due to a deploy failure that I missed.

**Comment by lukaskubanek** [comment]
> Seems my CI job that updates the formula failed

Glad to hear that there is an automation in place. After fixing this problem my issue should be resolved.

> Either way, I want a separate repo so when I release new tools in future I have one tap to contain the formula.

That makes sense. Thanks for explanation!

**Comment by mxcl** [comment]
I managed to fix the deployment today after many hours of batting my head against Travis. Formula is up to date again.
